### ISSUE TITLE
add compareIgnoringCase() and equalsIgnoringCase()

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#611]
We should add operations (toplevel functions or methods of `String`?) to compare `String`s case insensitively in the default locale.

In JavaScript this would need `localeCompare()`.

P.S. I'm not sure that our current implementation of `lowercased` and `uppercased` in JS is correct. I think it should use `toLocaleLowercase()` not `toLowercase()`. We need to check that.

Finally, it would be nice to have a `ignoringCase()` function for use with `byIncreasing()`/`byDecreasing()`.

**Comment by quintesse** [comment]
Just for easy reference:

[java.lang.Character.toUpperCase](http://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#toUpperCase(int))

[java.lang.String.toUpperCase](http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#toUpperCase())

[JS String.toLowerCase](http://www.ecma-international.org/ecma-262/5.1/#sec-15.5.4.16)

**Comment by gavinking** [comment]
Further problem: `String.compare()` in JS uses `localeCompare()`, which is dependent upon the default locale of the JS runtime, AFAICT. In Java we use `String.compareTo()`, which is not locale-sensitive.

**Comment by quintesse** [comment]
Looking at those pages maybe the best thing to so would be to use `toLocaleLowerCase()` in JavaScript so it will be on par with Java's `toLowerCase()`.

The problem is what to do with `Character.toLowerCase(). JavaScript doesn't have that obviously. And the thing is that a *true* uppercase conversion might result in several characters, that's why they say you should really be using `String.toLowerCase()` (which might result in a string of different length than the original!). If we would know what they do exactly in Java we might be able imitate it (perhaps use `String.toLowerCase()` and only return the first character?)

**Comment by gavinking** [comment]
@quintesse Well my inclination would be to do the opposite. I don't see why this stuff should be locale-dependent at all. I think we should always use the non-locale-dependent conversion, unless you explicitly make use of `ceylon.locale` to do a locale-aware operation.

**Comment by quintesse** [comment]
I don't agree, because this will result in the wrong result for all basic operations in 80% of the world. Meaning that everyone not speaking English will always have to reach for the locale package for even the most simple things. I think that in this day and age that is exactly the wrong thing to do.

Also in JS there's no proper definition of non-locale comparisons and [according to what I read](http://stackoverflow.com/questions/51165/how-do-you-do-string-comparison-in-javascript) the result is not defined (system and browser dependent). That way we'll never be able to get both backends to function the same.

The fix for the comparisons would be to use `Collator defaultCollator = Collator.getInstance();` for Java String comparisons.

**Comment by quintesse** [comment]
PS including others: @FroMage @tombentley @chochos

**Comment by gavinking** [comment]
@quintesse Java has a [`toUpperCase()` operation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase) that does not appear to depend upon locale.

Everything else can be defined in terms of that.

> Also in JS there's no proper definition of non-locale comparisons

The definition is totally trivial. Look at `String.compareTo()` in Java.

**Comment by gavinking** [comment]
> I don't agree, because this will result in the wrong result for all basic operations in 80% of the world. 

I think that's nonsense. The system default locale is already likely the wrong locale, at least it is in any server-side code.

**Comment by gavinking** [comment]
> I don't agree, because this will result in the wrong result for all basic operations in 80% of the world. 

By the way, it's also nonsense because the default behavior is correct essentially everywhere except Turkey. Turkey does not represent 80% of the global population.

**Comment by gavinking** [comment]
> the default behavior is correct essentially everywhere except Turkey.

OK, that's not quite right: apparently there's also a problem with Greek.

**Comment by quintesse** [comment]
>  the default behavior is correct essentially everywhere

For uppercase/lowercase yes, but for compare it's not. Heck Spain alone probably needs 4 different ones for each of its languages.

I agree that for sever environments the default locale won't be correct, but that's why in the end we'll need an easy way to set/override that default locale. If the default uppercase/lowercase/compare don't even take the locale into account we'll need a whole set of duplicate methods just like Java has.

And on the off chance that you *want* your application to work the same everywhere regardless of locale you just explicitly set it to ENGLISH.

Right now, everywhere in the world that's not England/US/Australia the first thing you do in Java when dealing with texts is import a whole bunch of extra classes to get the behaviour you want because all the defaults always only care about the English-speaking world.

In my opinion it would be really nice if we could do different.

**Comment by quintesse** [comment]
> Java has a toUpperCase() operation that does not appear to depend upon locale.

You provided a link to the JS uppercase here.
But it's exactly Java that does *not* have a locale-independent String.toUpperCase() although of course that would be easy enough to implement ourselves.

JAVA
String.toLowerCase() - locale dependent
Character.toLowerCase() - independent
String.compare() - independent
Using Collator compare() -  locale dependent

JavaScript
String.toLowerCase() - independent
String.toLocaleLowerCase() - locale dependent
Character.toLowerCase() - does not exist
String.compare() - dependent
String.localeCompare() - locale dependent

**Comment by quintesse** [comment]
Of course there's one thing to take into account here. Sometimes what you want is to know 100% that your code will act **exactly** the same way everywhere. In those cases being locale independent is an advantage.

**Comment by gavinking** [comment]
Folks we still need to urgently fix this for 1.2.

**Comment by gavinking** [comment]
All fixed up now.
