### ISSUE TITLE
ModelError at runtime with perfectly good metamodel code

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon.language#676]
```ceylon
class Foo(x) {
    shared Integer x;
}
class Bar(Integer x) extends Foo(x){

}
test
shared void e() {
    assert(is ValueDeclaration xDecl=`class Bar`.parameterDeclarations[0]);
    xDecl.memberGet(Bar(1));
}
```

it throws a com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Unsupported attribute type: Value[Bar.x:Integer]
at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1707)
at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1702)
at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedValue.initField(AppliedValue.java:171)

**Comment by FroMage** [comment]
So I think the exception is correct, because `Bar.x` is not captured so it's just not stored. Rename `Foo.x` to `Foo.y` to illustrate, or simply remove the `Foo` class entirely, and the same result will happen.

I do agree the error message is confusing so I'll change it to something like `attribute x is neither captured nor shared so it has no physical storage allocated and cannot be read by the metamodel`. Would that help, @tombentley ?

**Comment by tombentley** [comment]
Yes, I guess that would do. 

But I wonder what happens if we use a declaration literal to a non-shared, non-captured declaration -- I'd want that to be a compile time error, and I suspect it compiles just fine.

Also since capture is inherently platform specific I wonder how well defined and portable these circumstances truely are.

**Comment by FroMage** [comment]
Done.

**Comment by FroMage** [comment]
And no, we can't access them via literals: `ERROR: metamodel reference to local declaration`.
