### ISSUE TITLE
no way to discover constructors from `Class` model

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#695]
You can do things like `ClassOrInterface.getAttributes` or `ClassOrInterface.getMethods`, but there is no way to discover `Constructor`s - you have to know the name in advance and use `Class.getConstructor`.

**Comment by tombentley** [comment]
See #718. Given that proposal to resolve this issue we could add a `getConstructors()` to `ClassModel` which would return a `FunctionModel|ValueModel[]` refined to return a `Function|Value[]`  on `Class` and `Method|Attribute[]` on `MamberClass`. I'm not entirely sure whether this should include an element for the default constructor, but I'm inclined to think not (since the `Class` or `MemberClass` already represents that).

**Comment by tombentley** [comment]
The natural way for the model loader to load constructors if for it to find the java constructors. But for a value constructor the java constructor should be `private` (you get the instance from the getter). But it turns out that the `ClassMirror`s behave differently for javac and reflection versions: `JavacClass.getDirectMethods()` excludes private methods and constructors, but `ReflectionClass` includes them (because they're needed in order to support local declarations). 

It seems to me that it's simply wrong for the mirror implementations to behave differently -- the inclusion of exclusion of private members should be part of the mirror contract, and that worrying about private members should be a concern of the model loader itself rather than the mirrors. Unfortunately including private members for the JavacClass opens a load of other bugs...

**Comment by FroMage** [comment]
But why would you want the `JavacClass` to return private members? It's _only_ used by the compiler backend which does not care about private stuff.

AFAICT you only care about them at runtime in the metamodel, which does not use that, but uses `ReflectionClass` which will return them, so you're good, no?

**Comment by tombentley** [comment]
I had thought that the right API for this was to add 

    shared formal Sequential<FunctionModel<Type, Arguments>|ValueModel<Type>> getDeclaredConstructors
            <Arguments=Nothing>
            (ClosedType<Annotation>* annotationTypes)
                given Arguments satisfies Anything[];

to `ClassModel`, but I now realize that doesn't quite work. We usually use the `<Arguments>` type argument as a filter to find only things with a given argument list tuple type. But because the above API lumps callable constructors and value constructors together (and value constructors don't have argument lists), it doesn't work in an intuitive way. I suppose you could exclude the value constructors unless `Arguments=Nothing`.

I suppose it's OK to split the method in two, one to get matching callable constructors and another to get matching value constructors. That has the additional benefit of giving the method a for useful return type.

**Comment by gavinking** [comment]
No parameter list is a parameter list of type `Null`, surely?

**Comment by tombentley** [comment]
OK, we end up with `given Arguments satisfies Anything[]?`, but it all makes sense.

**Comment by tombentley** [comment]
Oh, except:

[ceylon-compile] /home/tom/ceylon/ceylon.language/src/ceylon/language/meta/model/ClassModel.ceylon:68: error: the 'SupertypeVisitor' caused an exception visiting a 'TypeConstraint' node: '"java.lang.RuntimeException: getSupertypes() not defined for union types or Nothing"' at 'com.redhat.ceylon.model.typechecker.model.Type.getSupertypes(Type.java:1370)'
[ceylon-compile]                 given Arguments satisfies Anything[]?;
[ceylon-compile]                 ^
[ceylon-compile] /home/tom/ceylon/ceylon.language/src/ceylon/language/meta/model/ClassModel.ceylon:68: error: upper bound must be a class, interface, or type parameter
[ceylon-compile]                 given Arguments satisfies Anything[]?;
[ceylon-compile]                                           ^

(i.e. an exception thrown in the tc, and using `Null` can't work, I love Mondays).

**Comment by gavinking** [comment]
Oh shit I see, that is not a legal type constraint. Damn!

**Comment by gavinking** [comment]
Heh. Can you report the exception please?

**Comment by tombentley** [comment]
I've implemented this for the JVM, awaiting implementation on JS.

**Comment by chochos** [comment]
@tombentley why on Earth does `getDeclaredValueConstructors()` return a no-arg callable constructor?

**Comment by chochos** [comment]
So this causes CCE:

```ceylon
class Outer {
  class Inner {
    shared new(){}
    shared new otro(){}
    shared new valor{}
  }
  shared void test() {
    value inner=`Inner`;
    for (cv in inner.getValueConstructors()) { //this causes CCE
      print(cv);
    }
  }
}
```

this is because `getValueConstructors` incorrectly includes callable constructors with no arguments.

**Comment by tombentley** [comment]
Well spotted @chochos -- the test was wrong so I'd written a callable ctor when I meant to by testing with a value ctor. So there's both now, and it should be fixed.
