### ISSUE TITLE
assert (is Comparable<Anything> x) should fail

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#723]
Object x = 1;
    assert (is Comparable<Anything> x)

Should fail.

**Comment by FroMage** [comment]
So this is actually due to the compiler having an optimisation for self-types, where it says that:

- because `Comparable` has a self-type bound on its type parameter,
- we can optimise the test as saying `is Comparable<X>` == `is X`

Except this doesn't work for invalid types, and `Comparable<Anything>` is actually not valid (or at least not inhabitable) because `Anything` does not satisfy `Comparable`. And with our optimisation, we transform it to `is Anything` which is always true.

So what can I call in the model to tell me this type makes no sense?

**Comment by gavinking** [comment]
@FroMage you have forgotten about: ceylon/ceylon-spec/issues/535

**Comment by FroMage** [comment]
Well, that came after this optimisation was added. Not that I understand why it's a feature and not a bug that we can denote uninhabited types, but hey…

**Comment by FroMage** [comment]
Fixed, I check that the type arg actually implements the interface now.

**Comment by gavinking** [comment]
> Not that I understand why it's a feature and not a bug that we can denote uninhabited types, but hey…

Well, try writing the type `Numeric<out Anything>`, the supertype of all instantiations of `Numeric` without this change.

**Comment by FroMage** [comment]
Oh, I see, OK.

**Comment by RossTate** [comment]
I'm curious, what's the use case that prompted this?

**Comment by bjorn** [comment]
@RossTate I came here from the following discussion on the Google Group, where somebody ran into this scenario: https://groups.google.com/forum/#!topic/ceylon-users/Tuawq2DIlfk

**Comment by RossTate** [comment]
Ah, ok. We sort of ruled out that use case as impractical, which is what I wanted to check.

Something I should note is that our study suggests that it would be entirely practical to disallow `is` checks with self types.
