### ISSUE TITLE
Add `undefined` constant

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#730]
To represent the `NaN` value whose name we are not allowed to pronounce, and have to call `undefined`, thereby causing confusion for JS coders we try to lure to Ceylon (the scaring of whom potentially being a good thing).

I'd also suggest renaming `Float.undefined` to `Float.notANumber` but I suppose it's too late?

Anyways, I sort of need that value to test #700, and it feels weird having to evaluate `0/0` just to get it.

@tombentley suggested adding it as a value constructor to `Float`, but then `infinity` is a toplevel, though we could make it point to `Float.infinity` for backwards compat, and add it there too for extra cleanliness.

**Comment by tombentley** [comment]
imo we should:

* add value constructors `Float.infinity` and `Float.nan` (I find `Float.notANumber` just unnecessarily difficult to type)
* deprecate top level `infinity` since it's been replaced by `Float.infinity`.
* retain the attribute `Float.undefined` as the test for NaN

I suppose we could deprecate `Float.undefined` and add `Float.isNan`, to make the naming more consistent.

**Comment by tombentley** [comment]
I've implemented this for JVM, but the metamodel tests fail: We need to merge the `ctor-model` branches before looking into that.

**Comment by gavinking** [comment]
I'm totally against this and it seems completely ill-conceived to me. _By definition_, the undefined value has no well defined equality or identity so representing it as a constant value is just going to cause people to shoot themselves in the foot in all sorts of ways. Furthermore, I can't think of _any_ usecase for wanting to pass the undefined value to a function. (Unlike `±infinity`, for which there _could_ be  meaningful return value.)

I don't know where this idea is coming from, but it seems that you need to go back and rethink your usecase because I can't see how it could possible be well-motivated.

May I close this issue please?

**Comment by gavinking** [comment]
And totally huge -1 on "nan" too. What kind of psychopath thinks "not a number" is a reasonable way to describe something?

As anyone who has ever studied high school mathematics knows, we say 

> zero divided by zero is undefined

i.e.

    (0/0).undefined

**Comment by FroMage** [comment]
> What kind of psychopath thinks "not a number" is a reasonable way to describe something?

Every programmer, not because it makes sense (like most words), because that's the convention.

> As anyone who has ever studied high school mathematics knows, we say "zero divided by zero is undefined"

Well, this is elitism. I'm not saying it's wrong at all. I'm saying the fact that it is known to math people doesn't mean it's known to most programmers. Not only that but I suggest this is widely dependent on language. I've never heard of that sort of definition in French. In fact I don't even recall being taught that in school, but if it were, it'd probably be defined as "you can't divide zero by zero".

You can't expect most programmers to be well versed in math terminology. Certainly not more so than computer science terminology, where that thing is definitely called NaN, for better or worse.

Again, I'm not saying we have to drop the math terminology, but at least make it programmer-friendly with an alias that they can discover. I've never heard of Ceylon being targeted at math people first so far, and I'm not sure that's something we should start doing.

**Comment by gavinking** [comment]
I didn't say anything about mathematicians. I'm using the terminology taught in _high school class_.

**Comment by tombentley** [comment]
There's a use case for these as constants when testing functions that take
floats, at least.

I don't really care about naming so long as people can find these thing by
the other name in things like the apidoc search. And ideally autocomplete.
The fact is that every other programming language calls this NaN, so that
is what people will look for and it's perverse if we don't help them find
it by that name. I don't care how we do that. Use an alias or add a synonym
annotation or whatever. But right now this stuff is not vet discoverable at
all.

**Comment by gavinking** [comment]
What are you guys even talking about? Hover over the identifier `Float` and tell me what you see.

**Comment by tombentley** [comment]
That is not a replacement for autocomplete. Users look for a method, then a
top-level and then are quite likely to give up. Users often don't read the
documentation.

**Comment by jvasileff** [comment]
Remember, this all started due to confusion over a (poorly written but correct as per junit) Java unit test of mine that looked like:
```
assertEquals(calcResultingInNaN(), Double.NaN)
```
@gavinking's ex post facto prediction nails it regarding the confusion:

1. Having a constant led to the false implication of equality
2. The name 'nan' sounds like an unavoidable marker value or error that might be equatable, not some more fundamental and meaningful mathematical concept that is neither equatable nor a value.

This unit test would have been written in a more readable fashion in Ceylon.

**Comment by gavinking** [comment]
Users who don't read documentation will google "ceylon nan" which will take them directly to a discussion #40 where we went through this design process. And where you @tombentley explained why there should be no constant value NaN.

P.S. Perhaps we should discuss whether `infinity` could be a value constructor of `Float` i.e. `Float.infinity`, but I don't see a strong reason to do that at this point.

**Comment by RossTate** [comment]
Aren't there multiple kinds of NaNs?

**Comment by tombentley** [comment]
There are, but Java conflates them all as a single one

**Comment by FroMage** [comment]
> I'm using the terminology taught in high school math class.

Again, this may be true for you, but not for everyone. This is not called `undefined` in French, but `forbidden`.

Now, if we have to get a little more pedantic, we haven't implemented any undefined behaviour: we have implemented the IEEE spec which calls these values `Not a Number`, not `undefined`. In fact it's precisely the opposite: it's very well _defined_ how these values work and interact.

**Comment by FroMage** [comment]
> Remember, this all started due to confusion over a (poorly written but correct as per junit) Java unit test of mine that looked like:

FTR, here's the current translated test:

```ceylon
    value nan = 0.0/0.0;
    check(nan.wholePart.undefined);
```

Sometimes, people have to work with IEEE, which we implement, whether we like it or not. And I strongly suspect that _anybody_ implementing serious things in math using floats have to deal with that standard's properties. Besides the naming of `undefined` that deviates from the standard and every other programming language I ever worked with, I don't see why we must make it hard to access those special values. Surely the people who care about them know how to get them because they know how they work, so it's not like we can hide them either (we do provide a test for that one), we're just pissing off people who have work to do with them.

**Comment by gavinking** [comment]
I don't think there should be a "constant" `undefined`. Nor do I think we should rename the attribute. Closing.

**Comment by FroMage** [comment]
Sigh. Can I add some docs to `Float` to explain howto get to one then?

**Comment by FroMage** [comment]
Well, in retrospect, perhaps at least part of this issue can be fixed using a doc alias like proposed in #734, so that people will find `notANumber` with completion.

**Comment by gavinking** [comment]
> perhaps at least part of this issue can be fixed using a doc alias like proposed

Precisely.

> Can I add some docs to `Float` to explain howto get to one then?

You mean like this:

> In addition, the following special values exist:
> 
> - [[infinity]] and `-infinity`, and
> - [[undefined values|undefined]], denoted [NaN][] by the
>   IEEE standard.
> 
> As required by the IEEE standard no undefined value is 
> equal to any other value, nor even to itself. Thus, the 
> definition of [[equals]] for `Float` violates the general 
> contract defined by [[Object.equals]].

**Comment by FroMage** [comment]
Well, it does not explain that if you need one you have to do `0/0`, that's what I'm proposing to add.

**Comment by gavinking** [comment]
OK, fine. But it's `0.0/0` you have to write.

**Comment by FroMage** [comment]
Ah yes, another reason to document it ;)

**Comment by gavinking** [comment]
It actually _is_ already documented if you look at `Float.undefined`.

**Comment by FroMage** [comment]
OK, true, that's good enough.

**Comment by FroMage** [comment]
Fixed.
