### ISSUE TITLE
What does `3/0` do?

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#765]
On the JVM it throws a JDK `ArithmeticException`. A Ceylon `Exception` on JS. Same goes for `remainder` and `modulo` (at least, perhaps other math operators?).

Do we want to specify that? Harmonise? If yes we'd need to stop generating native `/` operators on the JVM and invoke something like `Util.divideChecked(long, long)`.

I personally could not care less, so 1.3.

**Comment by FroMage** [comment]
OK this has already been discussed and the current behaviour was deemed acceptable. Closing.

**Comment by ePaul** [comment]
Is this previous discussion available for reading somewhere?

**Comment by tombentley** [comment]
I can't find where we decided that the current behaviour was acceptable explicitly, but there have been numerous discussions on the mailing list over the years. 

Essentially the problem is that on the JVM it's the VM itself which throws the exception, so we have no choice about what kind of exception gets thrown. We could check the divisor before every division operation and throw something else, but that would make every division *much* slower and division by zero is actually pretty rare. Then there's the fact that if your algorithm is going to divide by zero you would usually build in your own divisor check: You wouldn't usually catch the ArithmeticException. 

So having a common exception type across both backends is neither practical nor especially useful.
